### ISSUE TITLE
Error installing in VS Code 1.64.2

### ISSUE THREAD

**Issue by daironm-hillrom** [wallacegibbon/vsc-erlang-indent-with-emacs#1]
Thanks for this extension, I'm currently getting the following error while installing it:

Can't install 'wallacegibbon.erlang-indent-with-emacs' extension because it is not compatible with the current version of Visual Studio Code (version 1.64.2).

Any idea what could be the cause?

**Comment by wallacegibbon** [comment]
> 

I'm sorry but this extension only works for VSCode newer than "1.68.0".  (Which is defined in the auto-generated package.json)

Is it convenient for you to upgrade the VSCode to a newer version?

**Comment by daironm-hillrom** [comment]
It works for me now after upgrading. Mind if I explicitly add the version requirement to the README so it doesn't bite others?

**Comment by wallacegibbon** [comment]
> It works for me now after upgrading. Mind if I explicitly add the version requirement to the README so it doesn't bite others?

I have updated the README. Thank you for reporting this. 🤝
