### ISSUE TITLE
File with unicode in it

### ISSUE THREAD

**Issue by garazdawi** [wallacegibbon/vsc-erlang-indent-with-emacs#3]
If a file contains unicode, `get_region_points` calculates the region incorrectly which makes emacs fail to format.

To reproduce try to format this file:

```erlang
-module(test).
-export([go/0]).

go() ->
"😀".
```

It would seem like emacs expects the smilie to be a single character, while `get_region_points` counts it as 2 (which I assume is 2 UTF-16 "bytes").

I good workaround might be to not give a narroving region at all when doing "Format document"?

**Comment by wallacegibbon** [comment]
Really sorry for the late reply, I lost many github messages. The pull request is merged and I've published a new version to VSCode Marketplace. Thanks again for your contribution. 👍🏼

**Comment by garazdawi** [comment]
No worries, I've been running my own local copy of the extension while waiting for a new release. Thanks for a great extension :smile:
